### PR TITLE
Add conversion to rotation matrices

### PR DESCRIPTION
**Pull request by timholy**
Let me know if this seems useful, and if you want any changes.

### CODE REVIEW

**Comment by andreasnoack** [comment]
@WestleyArgentum I can offer to continue this package if you still don't plan to do so at Forio.

**Comment by WestleyArgentum** [comment]
Sorry, getting married tomorrow and totally distracted. I haven't actually been at Forio for a long time though and I don't have admin access to this. I can merge stuff, and I should be better about that, but the real answer is probably to talk with people there about turning it over. My guess is they'd be amenable to transferring the repo into a Julia organization perhaps, but I really don't know and will have to get back to you in a few days

**Comment by andreasnoack** [comment]
Sure. I hope you have had awonderful wedding. If it simplifies anything, we can transfer it to JuliaLang instead of my personal account. Thanks for taking care of this.

**Comment by andreasnoack** [comment]
bump

**Comment by WestleyArgentum** [comment]
@andreasnoack I merged your PR, will try and rebase and merge the others soon.

@wglasshusain what do you think about moving this repo into one of the Julia organizations so that more people can pitch in and maintain it? There have been a few PRs that I haven't been qualified to review, and I hate feeling like I'm slowing everyone down :)

**Comment by wglasshusain** [comment]
Hi Wes!  Like the new last name.   Does this mean that S. now has a triple hyphenated name?

I'm up for moving Quaternions.jl to one of the Julia organizations.  Do you want to start an email thread with the three of us (wglass@forio.com for me) to discuss?   Do you think the Julia organization would be interested in the other Forio-hosted Julia libraries (like the logging library Lumberjack.jl )?

WGH

**Pull request merged**
