### PR TITLE
Turn on precompilation and remove support for Julia 0.3

### PR DESCRIPTION
**Pull request by timholy**

### CODE REVIEW

**Comment by timholy** [comment]
Neither of those test failures seem real.

**Comment by c42f** [comment]
Please someone merge this!  Or at least merge #13 which has been hanging around for ages ;-)

**Comment by timholy** [comment]
Hmm, I didn't notice #13. Better to merge that one (priority matters), and then either I'll rebase this or whoever does the merge can drop the 0.3 support (so a new release can be tagged) and tag a new release.

FYI I cannot merge this. @SimonDanisch?

**Comment by SimonDanisch** [comment]
Woops, didn't see this! LGTM.
Will see if a restart of the build helps!

**Comment by SimonDanisch** [comment]
I merged the others as well, so the rebase would be needed now ;)

**Comment by SimonDanisch** [comment]
@timholy I sent you an invite to `JuliaGeometry`. Merge whenever you feel like ;)

**Pull request closed without merging**
